import Vue from 'vue'
import Router from 'vue-router'
import { normalizeURL, decode } from '@nuxt/ufo'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _6a1085f0 = () => interopDefault(import('..\\pages\\index.vue' /* webpackChunkName: "pages/index" */))
const _2563ddd0 = () => interopDefault(import('~/pages/index.vue' /* webpackChunkName: "" */))
const _b3c3f76a = () => interopDefault(import('..\\pages\\errors\\404.vue' /* webpackChunkName: "pages/errors/404" */))
const _9a2bdc60 = () => interopDefault(import('..\\pages\\z-archive\\widgets\\index.vue' /* webpackChunkName: "pages/z-archive/widgets/index" */))
const _5d3de145 = () => interopDefault(import('..\\pages\\z-archive\\account\\forgot-password.vue' /* webpackChunkName: "pages/z-archive/account/forgot-password" */))
const _2fd29ea9 = () => interopDefault(import('..\\pages\\z-archive\\account\\login.vue' /* webpackChunkName: "pages/z-archive/account/login" */))
const _2542e4da = () => interopDefault(import('..\\pages\\z-archive\\account\\register.vue' /* webpackChunkName: "pages/z-archive/account/register" */))
const _2f5ad3a5 = () => interopDefault(import('..\\pages\\z-archive\\apps\\calendar\\index.vue' /* webpackChunkName: "pages/z-archive/apps/calendar/index" */))
const _8469686a = () => interopDefault(import('..\\pages\\z-archive\\apps\\chat\\index.vue' /* webpackChunkName: "pages/z-archive/apps/chat/index" */))
const _58f0ba96 = () => interopDefault(import('..\\pages\\z-archive\\apps\\companies\\index.vue' /* webpackChunkName: "pages/z-archive/apps/companies/index" */))
const _bcaa4e4a = () => interopDefault(import('..\\pages\\z-archive\\apps\\file-manager.vue' /* webpackChunkName: "pages/z-archive/apps/file-manager" */))
const _531c33ca = () => interopDefault(import('..\\pages\\z-archive\\apps\\tickets\\index.vue' /* webpackChunkName: "pages/z-archive/apps/tickets/index" */))
const _05459a4e = () => interopDefault(import('..\\pages\\z-archive\\auth\\confirm-mail.vue' /* webpackChunkName: "pages/z-archive/auth/confirm-mail" */))
const _1548d1be = () => interopDefault(import('..\\pages\\z-archive\\auth\\confirm-mail-2.vue' /* webpackChunkName: "pages/z-archive/auth/confirm-mail-2" */))
const _2670ecae = () => interopDefault(import('..\\pages\\z-archive\\auth\\lock-screen.vue' /* webpackChunkName: "pages/z-archive/auth/lock-screen" */))
const _590e96e4 = () => interopDefault(import('..\\pages\\z-archive\\auth\\lock-screen-2.vue' /* webpackChunkName: "pages/z-archive/auth/lock-screen-2" */))
const _96f29af8 = () => interopDefault(import('..\\pages\\z-archive\\auth\\login.vue' /* webpackChunkName: "pages/z-archive/auth/login" */))
const _afdddaae = () => interopDefault(import('..\\pages\\z-archive\\auth\\login-2.vue' /* webpackChunkName: "pages/z-archive/auth/login-2" */))
const _2960a67f = () => interopDefault(import('..\\pages\\z-archive\\auth\\logout.vue' /* webpackChunkName: "pages/z-archive/auth/logout" */))
const _4e3df3e4 = () => interopDefault(import('..\\pages\\z-archive\\auth\\logout-2.vue' /* webpackChunkName: "pages/z-archive/auth/logout-2" */))
const _210cf64e = () => interopDefault(import('..\\pages\\z-archive\\auth\\recoverpwd.vue' /* webpackChunkName: "pages/z-archive/auth/recoverpwd" */))
const _0c158bf3 = () => interopDefault(import('..\\pages\\z-archive\\auth\\recoverpwd-2.vue' /* webpackChunkName: "pages/z-archive/auth/recoverpwd-2" */))
const _759db050 = () => interopDefault(import('..\\pages\\z-archive\\auth\\register.vue' /* webpackChunkName: "pages/z-archive/auth/register" */))
const _37f382fd = () => interopDefault(import('..\\pages\\z-archive\\auth\\register-2.vue' /* webpackChunkName: "pages/z-archive/auth/register-2" */))
const _91c55684 = () => interopDefault(import('..\\pages\\z-archive\\auth\\signin-signup.vue' /* webpackChunkName: "pages/z-archive/auth/signin-signup" */))
const _5f880e63 = () => interopDefault(import('..\\pages\\z-archive\\auth\\signin-signup-2.vue' /* webpackChunkName: "pages/z-archive/auth/signin-signup-2" */))
const _1b43ad7e = () => interopDefault(import('..\\pages\\z-archive\\charts\\apex\\index.vue' /* webpackChunkName: "pages/z-archive/charts/apex/index" */))
const _79ee5b30 = () => interopDefault(import('..\\pages\\z-archive\\charts\\c3\\index.vue' /* webpackChunkName: "pages/z-archive/charts/c3/index" */))
const _54d00518 = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartist\\index.vue' /* webpackChunkName: "pages/z-archive/charts/chartist/index" */))
const _38dfc3a6 = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartjs\\index.vue' /* webpackChunkName: "pages/z-archive/charts/chartjs/index" */))
const _1cf445d8 = () => interopDefault(import('..\\pages\\z-archive\\charts\\knob.vue' /* webpackChunkName: "pages/z-archive/charts/knob" */))
const _6e58713e = () => interopDefault(import('..\\pages\\z-archive\\contacts\\list.vue' /* webpackChunkName: "pages/z-archive/contacts/list" */))
const _0fee35b9 = () => interopDefault(import('..\\pages\\z-archive\\contacts\\profile.vue' /* webpackChunkName: "pages/z-archive/contacts/profile" */))
const _279933e3 = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\analytics\\index.vue' /* webpackChunkName: "pages/z-archive/dashboard/analytics/index" */))
const _071e41cb = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\crm\\index.vue' /* webpackChunkName: "pages/z-archive/dashboard/crm/index" */))
const _6a0e8a08 = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\default\\index.vue' /* webpackChunkName: "pages/z-archive/dashboard/default/index" */))
const _59610123 = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\cart.vue' /* webpackChunkName: "pages/z-archive/ecommerce/cart" */))
const _1bb2ba6e = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\checkout.vue' /* webpackChunkName: "pages/z-archive/ecommerce/checkout" */))
const _1c00e340 = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\customers\\index.vue' /* webpackChunkName: "pages/z-archive/ecommerce/customers/index" */))
const _85914e4a = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\data-products.js' /* webpackChunkName: "pages/z-archive/ecommerce/data-products" */))
const _5c57eab3 = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\order-detail.vue' /* webpackChunkName: "pages/z-archive/ecommerce/order-detail" */))
const _3b04d04c = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\orders\\index.vue' /* webpackChunkName: "pages/z-archive/ecommerce/orders/index" */))
const _5e0f5a46 = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\product-create.vue' /* webpackChunkName: "pages/z-archive/ecommerce/product-create" */))
const _b5b7ea8a = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\products\\index.vue' /* webpackChunkName: "pages/z-archive/ecommerce/products/index" */))
const _8d631bc8 = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\products-grid.vue' /* webpackChunkName: "pages/z-archive/ecommerce/products-grid" */))
const _467fabbe = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\sellers.vue' /* webpackChunkName: "pages/z-archive/ecommerce/sellers" */))
const _0c3174e6 = () => interopDefault(import('..\\pages\\z-archive\\email\\data-inbox.js' /* webpackChunkName: "pages/z-archive/email/data-inbox" */))
const _3395f092 = () => interopDefault(import('..\\pages\\z-archive\\email\\inbox.vue' /* webpackChunkName: "pages/z-archive/email/inbox" */))
const _47afc03e = () => interopDefault(import('..\\pages\\z-archive\\email\\sidepanel.vue' /* webpackChunkName: "pages/z-archive/email/sidepanel" */))
const _8156bb2c = () => interopDefault(import('..\\pages\\z-archive\\email\\templates.vue' /* webpackChunkName: "pages/z-archive/email/templates" */))
const _bc2a2828 = () => interopDefault(import('..\\pages\\z-archive\\email\\toolbar.vue' /* webpackChunkName: "pages/z-archive/email/toolbar" */))
const _6b4a39c8 = () => interopDefault(import('..\\pages\\z-archive\\extended\\rangeslider.vue' /* webpackChunkName: "pages/z-archive/extended/rangeslider" */))
const _4cd8c58e = () => interopDefault(import('..\\pages\\z-archive\\extended\\scrollspy.vue' /* webpackChunkName: "pages/z-archive/extended/scrollspy" */))
const _6527adae = () => interopDefault(import('..\\pages\\z-archive\\extended\\sweet-alert.vue' /* webpackChunkName: "pages/z-archive/extended/sweet-alert" */))
const _e68f3944 = () => interopDefault(import('..\\pages\\z-archive\\extended\\tour.vue' /* webpackChunkName: "pages/z-archive/extended/tour" */))
const _013e3478 = () => interopDefault(import('..\\pages\\z-archive\\extras\\404.vue' /* webpackChunkName: "pages/z-archive/extras/404" */))
const _4869a4d4 = () => interopDefault(import('..\\pages\\z-archive\\extras\\404-alt.vue' /* webpackChunkName: "pages/z-archive/extras/404-alt" */))
const _35ec11b5 = () => interopDefault(import('..\\pages\\z-archive\\extras\\500.vue' /* webpackChunkName: "pages/z-archive/extras/500" */))
const _2b407087 = () => interopDefault(import('..\\pages\\z-archive\\extras\\coming-soon.vue' /* webpackChunkName: "pages/z-archive/extras/coming-soon" */))
const _075096e6 = () => interopDefault(import('..\\pages\\z-archive\\extras\\faqs.vue' /* webpackChunkName: "pages/z-archive/extras/faqs" */))
const _437dd026 = () => interopDefault(import('..\\pages\\z-archive\\extras\\invoice.vue' /* webpackChunkName: "pages/z-archive/extras/invoice" */))
const _111bed65 = () => interopDefault(import('..\\pages\\z-archive\\extras\\lightbox.vue' /* webpackChunkName: "pages/z-archive/extras/lightbox" */))
const _6292d0d3 = () => interopDefault(import('..\\pages\\z-archive\\extras\\maintenance.vue' /* webpackChunkName: "pages/z-archive/extras/maintenance" */))
const _6e818006 = () => interopDefault(import('..\\pages\\z-archive\\extras\\pricing.vue' /* webpackChunkName: "pages/z-archive/extras/pricing" */))
const _06da3141 = () => interopDefault(import('..\\pages\\z-archive\\extras\\search-results.vue' /* webpackChunkName: "pages/z-archive/extras/search-results" */))
const _f9930516 = () => interopDefault(import('..\\pages\\z-archive\\extras\\sitemap.vue' /* webpackChunkName: "pages/z-archive/extras/sitemap" */))
const _7e16d762 = () => interopDefault(import('..\\pages\\z-archive\\extras\\starter.vue' /* webpackChunkName: "pages/z-archive/extras/starter" */))
const _7c1612b1 = () => interopDefault(import('..\\pages\\z-archive\\extras\\timeline.vue' /* webpackChunkName: "pages/z-archive/extras/timeline" */))
const _563bf658 = () => interopDefault(import('..\\pages\\z-archive\\forms\\advanced.vue' /* webpackChunkName: "pages/z-archive/forms/advanced" */))
const _0e88eb29 = () => interopDefault(import('..\\pages\\z-archive\\forms\\elements.vue' /* webpackChunkName: "pages/z-archive/forms/elements" */))
const _7ad82773 = () => interopDefault(import('..\\pages\\z-archive\\forms\\file-uploads.vue' /* webpackChunkName: "pages/z-archive/forms/file-uploads" */))
const _d7da68c4 = () => interopDefault(import('..\\pages\\z-archive\\forms\\mask.vue' /* webpackChunkName: "pages/z-archive/forms/mask" */))
const _50ef6a43 = () => interopDefault(import('..\\pages\\z-archive\\forms\\quill.vue' /* webpackChunkName: "pages/z-archive/forms/quill" */))
const _13f5832b = () => interopDefault(import('..\\pages\\z-archive\\forms\\validation.vue' /* webpackChunkName: "pages/z-archive/forms/validation" */))
const _40a6141d = () => interopDefault(import('..\\pages\\z-archive\\forms\\wizard.vue' /* webpackChunkName: "pages/z-archive/forms/wizard" */))
const _03275a0c = () => interopDefault(import('..\\pages\\z-archive\\icons\\boxicons.vue' /* webpackChunkName: "pages/z-archive/icons/boxicons" */))
const _46787261 = () => interopDefault(import('..\\pages\\z-archive\\icons\\data-fontawesome.js' /* webpackChunkName: "pages/z-archive/icons/data-fontawesome" */))
const _92931bdc = () => interopDefault(import('..\\pages\\z-archive\\icons\\data-material.js' /* webpackChunkName: "pages/z-archive/icons/data-material" */))
const _295a5aa8 = () => interopDefault(import('..\\pages\\z-archive\\icons\\data-remix.js' /* webpackChunkName: "pages/z-archive/icons/data-remix" */))
const _ebf12b54 = () => interopDefault(import('..\\pages\\z-archive\\icons\\feather.vue' /* webpackChunkName: "pages/z-archive/icons/feather" */))
const _3683f942 = () => interopDefault(import('..\\pages\\z-archive\\icons\\font-awesome.vue' /* webpackChunkName: "pages/z-archive/icons/font-awesome" */))
const _6613a536 = () => interopDefault(import('..\\pages\\z-archive\\icons\\mdi.vue' /* webpackChunkName: "pages/z-archive/icons/mdi" */))
const _24ca5e88 = () => interopDefault(import('..\\pages\\z-archive\\icons\\remix.vue' /* webpackChunkName: "pages/z-archive/icons/remix" */))
const _6d374927 = () => interopDefault(import('..\\pages\\z-archive\\icons\\weather.vue' /* webpackChunkName: "pages/z-archive/icons/weather" */))
const _31763a1d = () => interopDefault(import('..\\pages\\z-archive\\maps\\google.vue' /* webpackChunkName: "pages/z-archive/maps/google" */))
const _3961d924 = () => interopDefault(import('..\\pages\\z-archive\\tables\\advanced\\index.vue' /* webpackChunkName: "pages/z-archive/tables/advanced/index" */))
const _2c58452c = () => interopDefault(import('..\\pages\\z-archive\\tables\\basic.vue' /* webpackChunkName: "pages/z-archive/tables/basic" */))
const _a89f3bba = () => interopDefault(import('..\\pages\\z-archive\\task\\detail.vue' /* webpackChunkName: "pages/z-archive/task/detail" */))
const _47fad259 = () => interopDefault(import('..\\pages\\z-archive\\task\\kanban\\index.vue' /* webpackChunkName: "pages/z-archive/task/kanban/index" */))
const _52b69b20 = () => interopDefault(import('..\\pages\\z-archive\\task\\list.vue' /* webpackChunkName: "pages/z-archive/task/list" */))
const _c570152e = () => interopDefault(import('..\\pages\\z-archive\\ui\\avatars.vue' /* webpackChunkName: "pages/z-archive/ui/avatars" */))
const _1cbb4f30 = () => interopDefault(import('..\\pages\\z-archive\\ui\\buttons.vue' /* webpackChunkName: "pages/z-archive/ui/buttons" */))
const _37812fd2 = () => interopDefault(import('..\\pages\\z-archive\\ui\\cards.vue' /* webpackChunkName: "pages/z-archive/ui/cards" */))
const _75c49141 = () => interopDefault(import('..\\pages\\z-archive\\ui\\carousel.vue' /* webpackChunkName: "pages/z-archive/ui/carousel" */))
const _30ed5bf1 = () => interopDefault(import('..\\pages\\z-archive\\ui\\dropdowns.vue' /* webpackChunkName: "pages/z-archive/ui/dropdowns" */))
const _8e1ee5d2 = () => interopDefault(import('..\\pages\\z-archive\\ui\\general.vue' /* webpackChunkName: "pages/z-archive/ui/general" */))
const _3e6964a7 = () => interopDefault(import('..\\pages\\z-archive\\ui\\grid.vue' /* webpackChunkName: "pages/z-archive/ui/grid" */))
const _0a192499 = () => interopDefault(import('..\\pages\\z-archive\\ui\\images.vue' /* webpackChunkName: "pages/z-archive/ui/images" */))
const _21eb3631 = () => interopDefault(import('..\\pages\\z-archive\\ui\\list-group.vue' /* webpackChunkName: "pages/z-archive/ui/list-group" */))
const _09f7d687 = () => interopDefault(import('..\\pages\\z-archive\\ui\\modals.vue' /* webpackChunkName: "pages/z-archive/ui/modals" */))
const _75856852 = () => interopDefault(import('..\\pages\\z-archive\\ui\\notifications.vue' /* webpackChunkName: "pages/z-archive/ui/notifications" */))
const _721b6d1a = () => interopDefault(import('..\\pages\\z-archive\\ui\\portlets.vue' /* webpackChunkName: "pages/z-archive/ui/portlets" */))
const _3a05c38e = () => interopDefault(import('..\\pages\\z-archive\\ui\\progress.vue' /* webpackChunkName: "pages/z-archive/ui/progress" */))
const _3cf0380c = () => interopDefault(import('..\\pages\\z-archive\\ui\\ribbons.vue' /* webpackChunkName: "pages/z-archive/ui/ribbons" */))
const _4b83b74a = () => interopDefault(import('..\\pages\\z-archive\\ui\\spinners.vue' /* webpackChunkName: "pages/z-archive/ui/spinners" */))
const _feda53ee = () => interopDefault(import('..\\pages\\z-archive\\ui\\tabs-accordions.vue' /* webpackChunkName: "pages/z-archive/ui/tabs-accordions" */))
const _5b7c868c = () => interopDefault(import('..\\pages\\z-archive\\ui\\tooltips-popovers.vue' /* webpackChunkName: "pages/z-archive/ui/tooltips-popovers" */))
const _0a53f750 = () => interopDefault(import('..\\pages\\z-archive\\ui\\typography.vue' /* webpackChunkName: "pages/z-archive/ui/typography" */))
const _d6f7de2c = () => interopDefault(import('..\\pages\\z-archive\\ui\\video.vue' /* webpackChunkName: "pages/z-archive/ui/video" */))
const _524242f3 = () => interopDefault(import('..\\pages\\z-archive\\widgets\\data.js' /* webpackChunkName: "pages/z-archive/widgets/data" */))
const _6c5366bb = () => interopDefault(import('..\\pages\\z-archive\\apps\\calendar\\data-calendar.js' /* webpackChunkName: "pages/z-archive/apps/calendar/data-calendar" */))
const _3a8fbfae = () => interopDefault(import('..\\pages\\z-archive\\apps\\chat\\data.js' /* webpackChunkName: "pages/z-archive/apps/chat/data" */))
const _bd6f358e = () => interopDefault(import('..\\pages\\z-archive\\apps\\companies\\data.js' /* webpackChunkName: "pages/z-archive/apps/companies/data" */))
const _72a89b6d = () => interopDefault(import('..\\pages\\z-archive\\apps\\tickets\\data.js' /* webpackChunkName: "pages/z-archive/apps/tickets/data" */))
const _ebea1bbe = () => interopDefault(import('..\\pages\\z-archive\\charts\\apex\\data.js' /* webpackChunkName: "pages/z-archive/charts/apex/data" */))
const _0e896453 = () => interopDefault(import('..\\pages\\z-archive\\charts\\c3\\data.js' /* webpackChunkName: "pages/z-archive/charts/c3/data" */))
const _71fec797 = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartist\\data.js' /* webpackChunkName: "pages/z-archive/charts/chartist/data" */))
const _978bdbc0 = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartjs\\BarChart.vue' /* webpackChunkName: "pages/z-archive/charts/chartjs/BarChart" */))
const _43c0569e = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartjs\\DonutChart.vue' /* webpackChunkName: "pages/z-archive/charts/chartjs/DonutChart" */))
const _662c2005 = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartjs\\LineChart.vue' /* webpackChunkName: "pages/z-archive/charts/chartjs/LineChart" */))
const _5f5bf4c7 = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartjs\\PieChart.vue' /* webpackChunkName: "pages/z-archive/charts/chartjs/PieChart" */))
const _4a9db7d6 = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartjs\\PolarChart.vue' /* webpackChunkName: "pages/z-archive/charts/chartjs/PolarChart" */))
const _55b5314d = () => interopDefault(import('..\\pages\\z-archive\\charts\\chartjs\\RadarChart.vue' /* webpackChunkName: "pages/z-archive/charts/chartjs/RadarChart" */))
const _08c9be4f = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\analytics\\channels.vue' /* webpackChunkName: "pages/z-archive/dashboard/analytics/channels" */))
const _9a80e910 = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\analytics\\overview.vue' /* webpackChunkName: "pages/z-archive/dashboard/analytics/overview" */))
const _3a80ea83 = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\analytics\\social-media.vue' /* webpackChunkName: "pages/z-archive/dashboard/analytics/social-media" */))
const _de076cee = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\analytics\\sources.vue' /* webpackChunkName: "pages/z-archive/dashboard/analytics/sources" */))
const _6d030e19 = () => interopDefault(import('..\\pages\\z-archive\\dashboard\\analytics\\users.vue' /* webpackChunkName: "pages/z-archive/dashboard/analytics/users" */))
const _02a4b8fa = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\customers\\data.js' /* webpackChunkName: "pages/z-archive/ecommerce/customers/data" */))
const _3833c37d = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\orders\\data.js' /* webpackChunkName: "pages/z-archive/ecommerce/orders/data" */))
const _ec290ac4 = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\products\\data.js' /* webpackChunkName: "pages/z-archive/ecommerce/products/data" */))
const _76d1d7de = () => interopDefault(import('..\\pages\\z-archive\\tables\\advanced\\data.js' /* webpackChunkName: "pages/z-archive/tables/advanced/data" */))
const _6728dc88 = () => interopDefault(import('..\\pages\\z-archive\\task\\kanban\\data.js' /* webpackChunkName: "pages/z-archive/task/kanban/data" */))
const _2c0d76f8 = () => interopDefault(import('..\\pages\\z-archive\\ecommerce\\product-detail\\_id.vue' /* webpackChunkName: "pages/z-archive/ecommerce/product-detail/_id" */))
const _3563f153 = () => interopDefault(import('..\\pages\\z-archive\\email\\reademail\\_id.vue' /* webpackChunkName: "pages/z-archive/email/reademail/_id" */))

// TODO: remove in Nuxt 3
const emptyFn = () => {}
const originalPush = Router.prototype.push
Router.prototype.push = function push (location, onComplete = emptyFn, onAbort) {
  return originalPush.call(this, location, onComplete, onAbort)
}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _6a1085f0,
    name: "index___ar"
  }, {
    path: "/ar",
    component: _2563ddd0
  }, {
    path: "/es",
    component: _6a1085f0,
    name: "index___es"
  }, {
    path: "/es",
    component: _2563ddd0
  }, {
    path: "/fr",
    component: _6a1085f0,
    name: "index___fr"
  }, {
    path: "/fr",
    component: _2563ddd0
  }, {
    path: "/errors/404",
    component: _b3c3f76a,
    name: "errors-404___en"
  }, {
    path: "/z-archive/widgets",
    component: _9a2bdc60,
    name: "z-archive-widgets___en"
  }, {
    path: "/ar/errors/404",
    component: _b3c3f76a,
    name: "errors-404___ar"
  }, {
    path: "/ar/z-archive/widgets",
    component: _9a2bdc60,
    name: "z-archive-widgets___ar"
  }, {
    path: "/es/errors/404",
    component: _b3c3f76a,
    name: "errors-404___es"
  }, {
    path: "/es/z-archive/widgets",
    component: _9a2bdc60,
    name: "z-archive-widgets___es"
  }, {
    path: "/fr/errors/404",
    component: _b3c3f76a,
    name: "errors-404___fr"
  }, {
    path: "/fr/z-archive/widgets",
    component: _9a2bdc60,
    name: "z-archive-widgets___fr"
  }, {
    path: "/z-archive/account/forgot-password",
    component: _5d3de145,
    name: "z-archive-account-forgot-password___en"
  }, {
    path: "/z-archive/account/login",
    component: _2fd29ea9,
    name: "z-archive-account-login___en"
  }, {
    path: "/z-archive/account/register",
    component: _2542e4da,
    name: "z-archive-account-register___en"
  }, {
    path: "/z-archive/apps/calendar",
    component: _2f5ad3a5,
    name: "z-archive-apps-calendar___en"
  }, {
    path: "/z-archive/apps/chat",
    component: _8469686a,
    name: "z-archive-apps-chat___en"
  }, {
    path: "/z-archive/apps/companies",
    component: _58f0ba96,
    name: "z-archive-apps-companies___en"
  }, {
    path: "/z-archive/apps/file-manager",
    component: _bcaa4e4a,
    name: "z-archive-apps-file-manager___en"
  }, {
    path: "/z-archive/apps/tickets",
    component: _531c33ca,
    name: "z-archive-apps-tickets___en"
  }, {
    path: "/z-archive/auth/confirm-mail",
    component: _05459a4e,
    name: "z-archive-auth-confirm-mail___en"
  }, {
    path: "/z-archive/auth/confirm-mail-2",
    component: _1548d1be,
    name: "z-archive-auth-confirm-mail-2___en"
  }, {
    path: "/z-archive/auth/lock-screen",
    component: _2670ecae,
    name: "z-archive-auth-lock-screen___en"
  }, {
    path: "/z-archive/auth/lock-screen-2",
    component: _590e96e4,
    name: "z-archive-auth-lock-screen-2___en"
  }, {
    path: "/z-archive/auth/login",
    component: _96f29af8,
    name: "z-archive-auth-login___en"
  }, {
    path: "/z-archive/auth/login-2",
    component: _afdddaae,
    name: "z-archive-auth-login-2___en"
  }, {
    path: "/z-archive/auth/logout",
    component: _2960a67f,
    name: "z-archive-auth-logout___en"
  }, {
    path: "/z-archive/auth/logout-2",
    component: _4e3df3e4,
    name: "z-archive-auth-logout-2___en"
  }, {
    path: "/z-archive/auth/recoverpwd",
    component: _210cf64e,
    name: "z-archive-auth-recoverpwd___en"
  }, {
    path: "/z-archive/auth/recoverpwd-2",
    component: _0c158bf3,
    name: "z-archive-auth-recoverpwd-2___en"
  }, {
    path: "/z-archive/auth/register",
    component: _759db050,
    name: "z-archive-auth-register___en"
  }, {
    path: "/z-archive/auth/register-2",
    component: _37f382fd,
    name: "z-archive-auth-register-2___en"
  }, {
    path: "/z-archive/auth/signin-signup",
    component: _91c55684,
    name: "z-archive-auth-signin-signup___en"
  }, {
    path: "/z-archive/auth/signin-signup-2",
    component: _5f880e63,
    name: "z-archive-auth-signin-signup-2___en"
  }, {
    path: "/z-archive/charts/apex",
    component: _1b43ad7e,
    name: "z-archive-charts-apex___en"
  }, {
    path: "/z-archive/charts/c3",
    component: _79ee5b30,
    name: "z-archive-charts-c3___en"
  }, {
    path: "/z-archive/charts/chartist",
    component: _54d00518,
    name: "z-archive-charts-chartist___en"
  }, {
    path: "/z-archive/charts/chartjs",
    component: _38dfc3a6,
    name: "z-archive-charts-chartjs___en"
  }, {
    path: "/z-archive/charts/knob",
    component: _1cf445d8,
    name: "z-archive-charts-knob___en"
  }, {
    path: "/z-archive/contacts/list",
    component: _6e58713e,
    name: "z-archive-contacts-list___en"
  }, {
    path: "/z-archive/contacts/profile",
    component: _0fee35b9,
    name: "z-archive-contacts-profile___en"
  }, {
    path: "/z-archive/dashboard/analytics",
    component: _279933e3,
    name: "z-archive-dashboard-analytics___en"
  }, {
    path: "/z-archive/dashboard/crm",
    component: _071e41cb,
    name: "z-archive-dashboard-crm___en"
  }, {
    path: "/z-archive/dashboard/default",
    component: _6a0e8a08,
    name: "z-archive-dashboard-default___en"
  }, {
    path: "/z-archive/ecommerce/cart",
    component: _59610123,
    name: "z-archive-ecommerce-cart___en"
  }, {
    path: "/z-archive/ecommerce/checkout",
    component: _1bb2ba6e,
    name: "z-archive-ecommerce-checkout___en"
  }, {
    path: "/z-archive/ecommerce/customers",
    component: _1c00e340,
    name: "z-archive-ecommerce-customers___en"
  }, {
    path: "/z-archive/ecommerce/data-products",
    component: _85914e4a,
    name: "z-archive-ecommerce-data-products___en"
  }, {
    path: "/z-archive/ecommerce/order-detail",
    component: _5c57eab3,
    name: "z-archive-ecommerce-order-detail___en"
  }, {
    path: "/z-archive/ecommerce/orders",
    component: _3b04d04c,
    name: "z-archive-ecommerce-orders___en"
  }, {
    path: "/z-archive/ecommerce/product-create",
    component: _5e0f5a46,
    name: "z-archive-ecommerce-product-create___en"
  }, {
    path: "/z-archive/ecommerce/products",
    component: _b5b7ea8a,
    name: "z-archive-ecommerce-products___en"
  }, {
    path: "/z-archive/ecommerce/products-grid",
    component: _8d631bc8,
    name: "z-archive-ecommerce-products-grid___en"
  }, {
    path: "/z-archive/ecommerce/sellers",
    component: _467fabbe,
    name: "z-archive-ecommerce-sellers___en"
  }, {
    path: "/z-archive/email/data-inbox",
    component: _0c3174e6,
    name: "z-archive-email-data-inbox___en"
  }, {
    path: "/z-archive/email/inbox",
    component: _3395f092,
    name: "z-archive-email-inbox___en"
  }, {
    path: "/z-archive/email/sidepanel",
    component: _47afc03e,
    name: "z-archive-email-sidepanel___en"
  }, {
    path: "/z-archive/email/templates",
    component: _8156bb2c,
    name: "z-archive-email-templates___en"
  }, {
    path: "/z-archive/email/toolbar",
    component: _bc2a2828,
    name: "z-archive-email-toolbar___en"
  }, {
    path: "/z-archive/extended/rangeslider",
    component: _6b4a39c8,
    name: "z-archive-extended-rangeslider___en"
  }, {
    path: "/z-archive/extended/scrollspy",
    component: _4cd8c58e,
    name: "z-archive-extended-scrollspy___en"
  }, {
    path: "/z-archive/extended/sweet-alert",
    component: _6527adae,
    name: "z-archive-extended-sweet-alert___en"
  }, {
    path: "/z-archive/extended/tour",
    component: _e68f3944,
    name: "z-archive-extended-tour___en"
  }, {
    path: "/z-archive/extras/404",
    component: _013e3478,
    name: "z-archive-extras-404___en"
  }, {
    path: "/z-archive/extras/404-alt",
    component: _4869a4d4,
    name: "z-archive-extras-404-alt___en"
  }, {
    path: "/z-archive/extras/500",
    component: _35ec11b5,
    name: "z-archive-extras-500___en"
  }, {
    path: "/z-archive/extras/coming-soon",
    component: _2b407087,
    name: "z-archive-extras-coming-soon___en"
  }, {
    path: "/z-archive/extras/faqs",
    component: _075096e6,
    name: "z-archive-extras-faqs___en"
  }, {
    path: "/z-archive/extras/invoice",
    component: _437dd026,
    name: "z-archive-extras-invoice___en"
  }, {
    path: "/z-archive/extras/lightbox",
    component: _111bed65,
    name: "z-archive-extras-lightbox___en"
  }, {
    path: "/z-archive/extras/maintenance",
    component: _6292d0d3,
    name: "z-archive-extras-maintenance___en"
  }, {
    path: "/z-archive/extras/pricing",
    component: _6e818006,
    name: "z-archive-extras-pricing___en"
  }, {
    path: "/z-archive/extras/search-results",
    component: _06da3141,
    name: "z-archive-extras-search-results___en"
  }, {
    path: "/z-archive/extras/sitemap",
    component: _f9930516,
    name: "z-archive-extras-sitemap___en"
  }, {
    path: "/z-archive/extras/starter",
    component: _7e16d762,
    name: "z-archive-extras-starter___en"
  }, {
    path: "/z-archive/extras/timeline",
    component: _7c1612b1,
    name: "z-archive-extras-timeline___en"
  }, {
    path: "/z-archive/forms/advanced",
    component: _563bf658,
    name: "z-archive-forms-advanced___en"
  }, {
    path: "/z-archive/forms/elements",
    component: _0e88eb29,
    name: "z-archive-forms-elements___en"
  }, {
    path: "/z-archive/forms/file-uploads",
    component: _7ad82773,
    name: "z-archive-forms-file-uploads___en"
  }, {
    path: "/z-archive/forms/mask",
    component: _d7da68c4,
    name: "z-archive-forms-mask___en"
  }, {
    path: "/z-archive/forms/quill",
    component: _50ef6a43,
    name: "z-archive-forms-quill___en"
  }, {
    path: "/z-archive/forms/validation",
    component: _13f5832b,
    name: "z-archive-forms-validation___en"
  }, {
    path: "/z-archive/forms/wizard",
    component: _40a6141d,
    name: "z-archive-forms-wizard___en"
  }, {
    path: "/z-archive/icons/boxicons",
    component: _03275a0c,
    name: "z-archive-icons-boxicons___en"
  }, {
    path: "/z-archive/icons/data-fontawesome",
    component: _46787261,
    name: "z-archive-icons-data-fontawesome___en"
  }, {
    path: "/z-archive/icons/data-material",
    component: _92931bdc,
    name: "z-archive-icons-data-material___en"
  }, {
    path: "/z-archive/icons/data-remix",
    component: _295a5aa8,
    name: "z-archive-icons-data-remix___en"
  }, {
    path: "/z-archive/icons/feather",
    component: _ebf12b54,
    name: "z-archive-icons-feather___en"
  }, {
    path: "/z-archive/icons/font-awesome",
    component: _3683f942,
    name: "z-archive-icons-font-awesome___en"
  }, {
    path: "/z-archive/icons/mdi",
    component: _6613a536,
    name: "z-archive-icons-mdi___en"
  }, {
    path: "/z-archive/icons/remix",
    component: _24ca5e88,
    name: "z-archive-icons-remix___en"
  }, {
    path: "/z-archive/icons/weather",
    component: _6d374927,
    name: "z-archive-icons-weather___en"
  }, {
    path: "/z-archive/maps/google",
    component: _31763a1d,
    name: "z-archive-maps-google___en"
  }, {
    path: "/z-archive/tables/advanced",
    component: _3961d924,
    name: "z-archive-tables-advanced___en"
  }, {
    path: "/z-archive/tables/basic",
    component: _2c58452c,
    name: "z-archive-tables-basic___en"
  }, {
    path: "/z-archive/task/detail",
    component: _a89f3bba,
    name: "z-archive-task-detail___en"
  }, {
    path: "/z-archive/task/kanban",
    component: _47fad259,
    name: "z-archive-task-kanban___en"
  }, {
    path: "/z-archive/task/list",
    component: _52b69b20,
    name: "z-archive-task-list___en"
  }, {
    path: "/z-archive/ui/avatars",
    component: _c570152e,
    name: "z-archive-ui-avatars___en"
  }, {
    path: "/z-archive/ui/buttons",
    component: _1cbb4f30,
    name: "z-archive-ui-buttons___en"
  }, {
    path: "/z-archive/ui/cards",
    component: _37812fd2,
    name: "z-archive-ui-cards___en"
  }, {
    path: "/z-archive/ui/carousel",
    component: _75c49141,
    name: "z-archive-ui-carousel___en"
  }, {
    path: "/z-archive/ui/dropdowns",
    component: _30ed5bf1,
    name: "z-archive-ui-dropdowns___en"
  }, {
    path: "/z-archive/ui/general",
    component: _8e1ee5d2,
    name: "z-archive-ui-general___en"
  }, {
    path: "/z-archive/ui/grid",
    component: _3e6964a7,
    name: "z-archive-ui-grid___en"
  }, {
    path: "/z-archive/ui/images",
    component: _0a192499,
    name: "z-archive-ui-images___en"
  }, {
    path: "/z-archive/ui/list-group",
    component: _21eb3631,
    name: "z-archive-ui-list-group___en"
  }, {
    path: "/z-archive/ui/modals",
    component: _09f7d687,
    name: "z-archive-ui-modals___en"
  }, {
    path: "/z-archive/ui/notifications",
    component: _75856852,
    name: "z-archive-ui-notifications___en"
  }, {
    path: "/z-archive/ui/portlets",
    component: _721b6d1a,
    name: "z-archive-ui-portlets___en"
  }, {
    path: "/z-archive/ui/progress",
    component: _3a05c38e,
    name: "z-archive-ui-progress___en"
  }, {
    path: "/z-archive/ui/ribbons",
    component: _3cf0380c,
    name: "z-archive-ui-ribbons___en"
  }, {
    path: "/z-archive/ui/spinners",
    component: _4b83b74a,
    name: "z-archive-ui-spinners___en"
  }, {
    path: "/z-archive/ui/tabs-accordions",
    component: _feda53ee,
    name: "z-archive-ui-tabs-accordions___en"
  }, {
    path: "/z-archive/ui/tooltips-popovers",
    component: _5b7c868c,
    name: "z-archive-ui-tooltips-popovers___en"
  }, {
    path: "/z-archive/ui/typography",
    component: _0a53f750,
    name: "z-archive-ui-typography___en"
  }, {
    path: "/z-archive/ui/video",
    component: _d6f7de2c,
    name: "z-archive-ui-video___en"
  }, {
    path: "/z-archive/widgets/data",
    component: _524242f3,
    name: "z-archive-widgets-data___en"
  }, {
    path: "/ar/z-archive/account/forgot-password",
    component: _5d3de145,
    name: "z-archive-account-forgot-password___ar"
  }, {
    path: "/ar/z-archive/account/login",
    component: _2fd29ea9,
    name: "z-archive-account-login___ar"
  }, {
    path: "/ar/z-archive/account/register",
    component: _2542e4da,
    name: "z-archive-account-register___ar"
  }, {
    path: "/ar/z-archive/apps/calendar",
    component: _2f5ad3a5,
    name: "z-archive-apps-calendar___ar"
  }, {
    path: "/ar/z-archive/apps/chat",
    component: _8469686a,
    name: "z-archive-apps-chat___ar"
  }, {
    path: "/ar/z-archive/apps/companies",
    component: _58f0ba96,
    name: "z-archive-apps-companies___ar"
  }, {
    path: "/ar/z-archive/apps/file-manager",
    component: _bcaa4e4a,
    name: "z-archive-apps-file-manager___ar"
  }, {
    path: "/ar/z-archive/apps/tickets",
    component: _531c33ca,
    name: "z-archive-apps-tickets___ar"
  }, {
    path: "/ar/z-archive/auth/confirm-mail",
    component: _05459a4e,
    name: "z-archive-auth-confirm-mail___ar"
  }, {
    path: "/ar/z-archive/auth/confirm-mail-2",
    component: _1548d1be,
    name: "z-archive-auth-confirm-mail-2___ar"
  }, {
    path: "/ar/z-archive/auth/lock-screen",
    component: _2670ecae,
    name: "z-archive-auth-lock-screen___ar"
  }, {
    path: "/ar/z-archive/auth/lock-screen-2",
    component: _590e96e4,
    name: "z-archive-auth-lock-screen-2___ar"
  }, {
    path: "/ar/z-archive/auth/login",
    component: _96f29af8,
    name: "z-archive-auth-login___ar"
  }, {
    path: "/ar/z-archive/auth/login-2",
    component: _afdddaae,
    name: "z-archive-auth-login-2___ar"
  }, {
    path: "/ar/z-archive/auth/logout",
    component: _2960a67f,
    name: "z-archive-auth-logout___ar"
  }, {
    path: "/ar/z-archive/auth/logout-2",
    component: _4e3df3e4,
    name: "z-archive-auth-logout-2___ar"
  }, {
    path: "/ar/z-archive/auth/recoverpwd",
    component: _210cf64e,
    name: "z-archive-auth-recoverpwd___ar"
  }, {
    path: "/ar/z-archive/auth/recoverpwd-2",
    component: _0c158bf3,
    name: "z-archive-auth-recoverpwd-2___ar"
  }, {
    path: "/ar/z-archive/auth/register",
    component: _759db050,
    name: "z-archive-auth-register___ar"
  }, {
    path: "/ar/z-archive/auth/register-2",
    component: _37f382fd,
    name: "z-archive-auth-register-2___ar"
  }, {
    path: "/ar/z-archive/auth/signin-signup",
    component: _91c55684,
    name: "z-archive-auth-signin-signup___ar"
  }, {
    path: "/ar/z-archive/auth/signin-signup-2",
    component: _5f880e63,
    name: "z-archive-auth-signin-signup-2___ar"
  }, {
    path: "/ar/z-archive/charts/apex",
    component: _1b43ad7e,
    name: "z-archive-charts-apex___ar"
  }, {
    path: "/ar/z-archive/charts/c3",
    component: _79ee5b30,
    name: "z-archive-charts-c3___ar"
  }, {
    path: "/ar/z-archive/charts/chartist",
    component: _54d00518,
    name: "z-archive-charts-chartist___ar"
  }, {
    path: "/ar/z-archive/charts/chartjs",
    component: _38dfc3a6,
    name: "z-archive-charts-chartjs___ar"
  }, {
    path: "/ar/z-archive/charts/knob",
    component: _1cf445d8,
    name: "z-archive-charts-knob___ar"
  }, {
    path: "/ar/z-archive/contacts/list",
    component: _6e58713e,
    name: "z-archive-contacts-list___ar"
  }, {
    path: "/ar/z-archive/contacts/profile",
    component: _0fee35b9,
    name: "z-archive-contacts-profile___ar"
  }, {
    path: "/ar/z-archive/dashboard/analytics",
    component: _279933e3,
    name: "z-archive-dashboard-analytics___ar"
  }, {
    path: "/ar/z-archive/dashboard/crm",
    component: _071e41cb,
    name: "z-archive-dashboard-crm___ar"
  }, {
    path: "/ar/z-archive/dashboard/default",
    component: _6a0e8a08,
    name: "z-archive-dashboard-default___ar"
  }, {
    path: "/ar/z-archive/ecommerce/cart",
    component: _59610123,
    name: "z-archive-ecommerce-cart___ar"
  }, {
    path: "/ar/z-archive/ecommerce/checkout",
    component: _1bb2ba6e,
    name: "z-archive-ecommerce-checkout___ar"
  }, {
    path: "/ar/z-archive/ecommerce/customers",
    component: _1c00e340,
    name: "z-archive-ecommerce-customers___ar"
  }, {
    path: "/ar/z-archive/ecommerce/data-products",
    component: _85914e4a,
    name: "z-archive-ecommerce-data-products___ar"
  }, {
    path: "/ar/z-archive/ecommerce/order-detail",
    component: _5c57eab3,
    name: "z-archive-ecommerce-order-detail___ar"
  }, {
    path: "/ar/z-archive/ecommerce/orders",
    component: _3b04d04c,
    name: "z-archive-ecommerce-orders___ar"
  }, {
    path: "/ar/z-archive/ecommerce/product-create",
    component: _5e0f5a46,
    name: "z-archive-ecommerce-product-create___ar"
  }, {
    path: "/ar/z-archive/ecommerce/products",
    component: _b5b7ea8a,
    name: "z-archive-ecommerce-products___ar"
  }, {
    path: "/ar/z-archive/ecommerce/products-grid",
    component: _8d631bc8,
    name: "z-archive-ecommerce-products-grid___ar"
  }, {
    path: "/ar/z-archive/ecommerce/sellers",
    component: _467fabbe,
    name: "z-archive-ecommerce-sellers___ar"
  }, {
    path: "/ar/z-archive/email/data-inbox",
    component: _0c3174e6,
    name: "z-archive-email-data-inbox___ar"
  }, {
    path: "/ar/z-archive/email/inbox",
    component: _3395f092,
    name: "z-archive-email-inbox___ar"
  }, {
    path: "/ar/z-archive/email/sidepanel",
    component: _47afc03e,
    name: "z-archive-email-sidepanel___ar"
  }, {
    path: "/ar/z-archive/email/templates",
    component: _8156bb2c,
    name: "z-archive-email-templates___ar"
  }, {
    path: "/ar/z-archive/email/toolbar",
    component: _bc2a2828,
    name: "z-archive-email-toolbar___ar"
  }, {
    path: "/ar/z-archive/extended/rangeslider",
    component: _6b4a39c8,
    name: "z-archive-extended-rangeslider___ar"
  }, {
    path: "/ar/z-archive/extended/scrollspy",
    component: _4cd8c58e,
    name: "z-archive-extended-scrollspy___ar"
  }, {
    path: "/ar/z-archive/extended/sweet-alert",
    component: _6527adae,
    name: "z-archive-extended-sweet-alert___ar"
  }, {
    path: "/ar/z-archive/extended/tour",
    component: _e68f3944,
    name: "z-archive-extended-tour___ar"
  }, {
    path: "/ar/z-archive/extras/404",
    component: _013e3478,
    name: "z-archive-extras-404___ar"
  }, {
    path: "/ar/z-archive/extras/404-alt",
    component: _4869a4d4,
    name: "z-archive-extras-404-alt___ar"
  }, {
    path: "/ar/z-archive/extras/500",
    component: _35ec11b5,
    name: "z-archive-extras-500___ar"
  }, {
    path: "/ar/z-archive/extras/coming-soon",
    component: _2b407087,
    name: "z-archive-extras-coming-soon___ar"
  }, {
    path: "/ar/z-archive/extras/faqs",
    component: _075096e6,
    name: "z-archive-extras-faqs___ar"
  }, {
    path: "/ar/z-archive/extras/invoice",
    component: _437dd026,
    name: "z-archive-extras-invoice___ar"
  }, {
    path: "/ar/z-archive/extras/lightbox",
    component: _111bed65,
    name: "z-archive-extras-lightbox___ar"
  }, {
    path: "/ar/z-archive/extras/maintenance",
    component: _6292d0d3,
    name: "z-archive-extras-maintenance___ar"
  }, {
    path: "/ar/z-archive/extras/pricing",
    component: _6e818006,
    name: "z-archive-extras-pricing___ar"
  }, {
    path: "/ar/z-archive/extras/search-results",
    component: _06da3141,
    name: "z-archive-extras-search-results___ar"
  }, {
    path: "/ar/z-archive/extras/sitemap",
    component: _f9930516,
    name: "z-archive-extras-sitemap___ar"
  }, {
    path: "/ar/z-archive/extras/starter",
    component: _7e16d762,
    name: "z-archive-extras-starter___ar"
  }, {
    path: "/ar/z-archive/extras/timeline",
    component: _7c1612b1,
    name: "z-archive-extras-timeline___ar"
  }, {
    path: "/ar/z-archive/forms/advanced",
    component: _563bf658,
    name: "z-archive-forms-advanced___ar"
  }, {
    path: "/ar/z-archive/forms/elements",
    component: _0e88eb29,
    name: "z-archive-forms-elements___ar"
  }, {
    path: "/ar/z-archive/forms/file-uploads",
    component: _7ad82773,
    name: "z-archive-forms-file-uploads___ar"
  }, {
    path: "/ar/z-archive/forms/mask",
    component: _d7da68c4,
    name: "z-archive-forms-mask___ar"
  }, {
    path: "/ar/z-archive/forms/quill",
    component: _50ef6a43,
    name: "z-archive-forms-quill___ar"
  }, {
    path: "/ar/z-archive/forms/validation",
    component: _13f5832b,
    name: "z-archive-forms-validation___ar"
  }, {
    path: "/ar/z-archive/forms/wizard",
    component: _40a6141d,
    name: "z-archive-forms-wizard___ar"
  }, {
    path: "/ar/z-archive/icons/boxicons",
    component: _03275a0c,
    name: "z-archive-icons-boxicons___ar"
  }, {
    path: "/ar/z-archive/icons/data-fontawesome",
    component: _46787261,
    name: "z-archive-icons-data-fontawesome___ar"
  }, {
    path: "/ar/z-archive/icons/data-material",
    component: _92931bdc,
    name: "z-archive-icons-data-material___ar"
  }, {
    path: "/ar/z-archive/icons/data-remix",
    component: _295a5aa8,
    name: "z-archive-icons-data-remix___ar"
  }, {
    path: "/ar/z-archive/icons/feather",
    component: _ebf12b54,
    name: "z-archive-icons-feather___ar"
  }, {
    path: "/ar/z-archive/icons/font-awesome",
    component: _3683f942,
    name: "z-archive-icons-font-awesome___ar"
  }, {
    path: "/ar/z-archive/icons/mdi",
    component: _6613a536,
    name: "z-archive-icons-mdi___ar"
  }, {
    path: "/ar/z-archive/icons/remix",
    component: _24ca5e88,
    name: "z-archive-icons-remix___ar"
  }, {
    path: "/ar/z-archive/icons/weather",
    component: _6d374927,
    name: "z-archive-icons-weather___ar"
  }, {
    path: "/ar/z-archive/maps/google",
    component: _31763a1d,
    name: "z-archive-maps-google___ar"
  }, {
    path: "/ar/z-archive/tables/advanced",
    component: _3961d924,
    name: "z-archive-tables-advanced___ar"
  }, {
    path: "/ar/z-archive/tables/basic",
    component: _2c58452c,
    name: "z-archive-tables-basic___ar"
  }, {
    path: "/ar/z-archive/task/detail",
    component: _a89f3bba,
    name: "z-archive-task-detail___ar"
  }, {
    path: "/ar/z-archive/task/kanban",
    component: _47fad259,
    name: "z-archive-task-kanban___ar"
  }, {
    path: "/ar/z-archive/task/list",
    component: _52b69b20,
    name: "z-archive-task-list___ar"
  }, {
    path: "/ar/z-archive/ui/avatars",
    component: _c570152e,
    name: "z-archive-ui-avatars___ar"
  }, {
    path: "/ar/z-archive/ui/buttons",
    component: _1cbb4f30,
    name: "z-archive-ui-buttons___ar"
  }, {
    path: "/ar/z-archive/ui/cards",
    component: _37812fd2,
    name: "z-archive-ui-cards___ar"
  }, {
    path: "/ar/z-archive/ui/carousel",
    component: _75c49141,
    name: "z-archive-ui-carousel___ar"
  }, {
    path: "/ar/z-archive/ui/dropdowns",
    component: _30ed5bf1,
    name: "z-archive-ui-dropdowns___ar"
  }, {
    path: "/ar/z-archive/ui/general",
    component: _8e1ee5d2,
    name: "z-archive-ui-general___ar"
  }, {
    path: "/ar/z-archive/ui/grid",
    component: _3e6964a7,
    name: "z-archive-ui-grid___ar"
  }, {
    path: "/ar/z-archive/ui/images",
    component: _0a192499,
    name: "z-archive-ui-images___ar"
  }, {
    path: "/ar/z-archive/ui/list-group",
    component: _21eb3631,
    name: "z-archive-ui-list-group___ar"
  }, {
    path: "/ar/z-archive/ui/modals",
    component: _09f7d687,
    name: "z-archive-ui-modals___ar"
  }, {
    path: "/ar/z-archive/ui/notifications",
    component: _75856852,
    name: "z-archive-ui-notifications___ar"
  }, {
    path: "/ar/z-archive/ui/portlets",
    component: _721b6d1a,
    name: "z-archive-ui-portlets___ar"
  }, {
    path: "/ar/z-archive/ui/progress",
    component: _3a05c38e,
    name: "z-archive-ui-progress___ar"
  }, {
    path: "/ar/z-archive/ui/ribbons",
    component: _3cf0380c,
    name: "z-archive-ui-ribbons___ar"
  }, {
    path: "/ar/z-archive/ui/spinners",
    component: _4b83b74a,
    name: "z-archive-ui-spinners___ar"
  }, {
    path: "/ar/z-archive/ui/tabs-accordions",
    component: _feda53ee,
    name: "z-archive-ui-tabs-accordions___ar"
  }, {
    path: "/ar/z-archive/ui/tooltips-popovers",
    component: _5b7c868c,
    name: "z-archive-ui-tooltips-popovers___ar"
  }, {
    path: "/ar/z-archive/ui/typography",
    component: _0a53f750,
    name: "z-archive-ui-typography___ar"
  }, {
    path: "/ar/z-archive/ui/video",
    component: _d6f7de2c,
    name: "z-archive-ui-video___ar"
  }, {
    path: "/ar/z-archive/widgets/data",
    component: _524242f3,
    name: "z-archive-widgets-data___ar"
  }, {
    path: "/es/z-archive/account/forgot-password",
    component: _5d3de145,
    name: "z-archive-account-forgot-password___es"
  }, {
    path: "/es/z-archive/account/login",
    component: _2fd29ea9,
    name: "z-archive-account-login___es"
  }, {
    path: "/es/z-archive/account/register",
    component: _2542e4da,
    name: "z-archive-account-register___es"
  }, {
    path: "/es/z-archive/apps/calendar",
    component: _2f5ad3a5,
    name: "z-archive-apps-calendar___es"
  }, {
    path: "/es/z-archive/apps/chat",
    component: _8469686a,
    name: "z-archive-apps-chat___es"
  }, {
    path: "/es/z-archive/apps/companies",
    component: _58f0ba96,
    name: "z-archive-apps-companies___es"
  }, {
    path: "/es/z-archive/apps/file-manager",
    component: _bcaa4e4a,
    name: "z-archive-apps-file-manager___es"
  }, {
    path: "/es/z-archive/apps/tickets",
    component: _531c33ca,
    name: "z-archive-apps-tickets___es"
  }, {
    path: "/es/z-archive/auth/confirm-mail",
    component: _05459a4e,
    name: "z-archive-auth-confirm-mail___es"
  }, {
    path: "/es/z-archive/auth/confirm-mail-2",
    component: _1548d1be,
    name: "z-archive-auth-confirm-mail-2___es"
  }, {
    path: "/es/z-archive/auth/lock-screen",
    component: _2670ecae,
    name: "z-archive-auth-lock-screen___es"
  }, {
    path: "/es/z-archive/auth/lock-screen-2",
    component: _590e96e4,
    name: "z-archive-auth-lock-screen-2___es"
  }, {
    path: "/es/z-archive/auth/login",
    component: _96f29af8,
    name: "z-archive-auth-login___es"
  }, {
    path: "/es/z-archive/auth/login-2",
    component: _afdddaae,
    name: "z-archive-auth-login-2___es"
  }, {
    path: "/es/z-archive/auth/logout",
    component: _2960a67f,
    name: "z-archive-auth-logout___es"
  }, {
    path: "/es/z-archive/auth/logout-2",
    component: _4e3df3e4,
    name: "z-archive-auth-logout-2___es"
  }, {
    path: "/es/z-archive/auth/recoverpwd",
    component: _210cf64e,
    name: "z-archive-auth-recoverpwd___es"
  }, {
    path: "/es/z-archive/auth/recoverpwd-2",
    component: _0c158bf3,
    name: "z-archive-auth-recoverpwd-2___es"
  }, {
    path: "/es/z-archive/auth/register",
    component: _759db050,
    name: "z-archive-auth-register___es"
  }, {
    path: "/es/z-archive/auth/register-2",
    component: _37f382fd,
    name: "z-archive-auth-register-2___es"
  }, {
    path: "/es/z-archive/auth/signin-signup",
    component: _91c55684,
    name: "z-archive-auth-signin-signup___es"
  }, {
    path: "/es/z-archive/auth/signin-signup-2",
    component: _5f880e63,
    name: "z-archive-auth-signin-signup-2___es"
  }, {
    path: "/es/z-archive/charts/apex",
    component: _1b43ad7e,
    name: "z-archive-charts-apex___es"
  }, {
    path: "/es/z-archive/charts/c3",
    component: _79ee5b30,
    name: "z-archive-charts-c3___es"
  }, {
    path: "/es/z-archive/charts/chartist",
    component: _54d00518,
    name: "z-archive-charts-chartist___es"
  }, {
    path: "/es/z-archive/charts/chartjs",
    component: _38dfc3a6,
    name: "z-archive-charts-chartjs___es"
  }, {
    path: "/es/z-archive/charts/knob",
    component: _1cf445d8,
    name: "z-archive-charts-knob___es"
  }, {
    path: "/es/z-archive/contacts/list",
    component: _6e58713e,
    name: "z-archive-contacts-list___es"
  }, {
    path: "/es/z-archive/contacts/profile",
    component: _0fee35b9,
    name: "z-archive-contacts-profile___es"
  }, {
    path: "/es/z-archive/dashboard/analytics",
    component: _279933e3,
    name: "z-archive-dashboard-analytics___es"
  }, {
    path: "/es/z-archive/dashboard/crm",
    component: _071e41cb,
    name: "z-archive-dashboard-crm___es"
  }, {
    path: "/es/z-archive/dashboard/default",
    component: _6a0e8a08,
    name: "z-archive-dashboard-default___es"
  }, {
    path: "/es/z-archive/ecommerce/cart",
    component: _59610123,
    name: "z-archive-ecommerce-cart___es"
  }, {
    path: "/es/z-archive/ecommerce/checkout",
    component: _1bb2ba6e,
    name: "z-archive-ecommerce-checkout___es"
  }, {
    path: "/es/z-archive/ecommerce/customers",
    component: _1c00e340,
    name: "z-archive-ecommerce-customers___es"
  }, {
    path: "/es/z-archive/ecommerce/data-products",
    component: _85914e4a,
    name: "z-archive-ecommerce-data-products___es"
  }, {
    path: "/es/z-archive/ecommerce/order-detail",
    component: _5c57eab3,
    name: "z-archive-ecommerce-order-detail___es"
  }, {
    path: "/es/z-archive/ecommerce/orders",
    component: _3b04d04c,
    name: "z-archive-ecommerce-orders___es"
  }, {
    path: "/es/z-archive/ecommerce/product-create",
    component: _5e0f5a46,
    name: "z-archive-ecommerce-product-create___es"
  }, {
    path: "/es/z-archive/ecommerce/products",
    component: _b5b7ea8a,
    name: "z-archive-ecommerce-products___es"
  }, {
    path: "/es/z-archive/ecommerce/products-grid",
    component: _8d631bc8,
    name: "z-archive-ecommerce-products-grid___es"
  }, {
    path: "/es/z-archive/ecommerce/sellers",
    component: _467fabbe,
    name: "z-archive-ecommerce-sellers___es"
  }, {
    path: "/es/z-archive/email/data-inbox",
    component: _0c3174e6,
    name: "z-archive-email-data-inbox___es"
  }, {
    path: "/es/z-archive/email/inbox",
    component: _3395f092,
    name: "z-archive-email-inbox___es"
  }, {
    path: "/es/z-archive/email/sidepanel",
    component: _47afc03e,
    name: "z-archive-email-sidepanel___es"
  }, {
    path: "/es/z-archive/email/templates",
    component: _8156bb2c,
    name: "z-archive-email-templates___es"
  }, {
    path: "/es/z-archive/email/toolbar",
    component: _bc2a2828,
    name: "z-archive-email-toolbar___es"
  }, {
    path: "/es/z-archive/extended/rangeslider",
    component: _6b4a39c8,
    name: "z-archive-extended-rangeslider___es"
  }, {
    path: "/es/z-archive/extended/scrollspy",
    component: _4cd8c58e,
    name: "z-archive-extended-scrollspy___es"
  }, {
    path: "/es/z-archive/extended/sweet-alert",
    component: _6527adae,
    name: "z-archive-extended-sweet-alert___es"
  }, {
    path: "/es/z-archive/extended/tour",
    component: _e68f3944,
    name: "z-archive-extended-tour___es"
  }, {
    path: "/es/z-archive/extras/404",
    component: _013e3478,
    name: "z-archive-extras-404___es"
  }, {
    path: "/es/z-archive/extras/404-alt",
    component: _4869a4d4,
    name: "z-archive-extras-404-alt___es"
  }, {
    path: "/es/z-archive/extras/500",
    component: _35ec11b5,
    name: "z-archive-extras-500___es"
  }, {
    path: "/es/z-archive/extras/coming-soon",
    component: _2b407087,
    name: "z-archive-extras-coming-soon___es"
  }, {
    path: "/es/z-archive/extras/faqs",
    component: _075096e6,
    name: "z-archive-extras-faqs___es"
  }, {
    path: "/es/z-archive/extras/invoice",
    component: _437dd026,
    name: "z-archive-extras-invoice___es"
  }, {
    path: "/es/z-archive/extras/lightbox",
    component: _111bed65,
    name: "z-archive-extras-lightbox___es"
  }, {
    path: "/es/z-archive/extras/maintenance",
    component: _6292d0d3,
    name: "z-archive-extras-maintenance___es"
  }, {
    path: "/es/z-archive/extras/pricing",
    component: _6e818006,
    name: "z-archive-extras-pricing___es"
  }, {
    path: "/es/z-archive/extras/search-results",
    component: _06da3141,
    name: "z-archive-extras-search-results___es"
  }, {
    path: "/es/z-archive/extras/sitemap",
    component: _f9930516,
    name: "z-archive-extras-sitemap___es"
  }, {
    path: "/es/z-archive/extras/starter",
    component: _7e16d762,
    name: "z-archive-extras-starter___es"
  }, {
    path: "/es/z-archive/extras/timeline",
    component: _7c1612b1,
    name: "z-archive-extras-timeline___es"
  }, {
    path: "/es/z-archive/forms/advanced",
    component: _563bf658,
    name: "z-archive-forms-advanced___es"
  }, {
    path: "/es/z-archive/forms/elements",
    component: _0e88eb29,
    name: "z-archive-forms-elements___es"
  }, {
    path: "/es/z-archive/forms/file-uploads",
    component: _7ad82773,
    name: "z-archive-forms-file-uploads___es"
  }, {
    path: "/es/z-archive/forms/mask",
    component: _d7da68c4,
    name: "z-archive-forms-mask___es"
  }, {
    path: "/es/z-archive/forms/quill",
    component: _50ef6a43,
    name: "z-archive-forms-quill___es"
  }, {
    path: "/es/z-archive/forms/validation",
    component: _13f5832b,
    name: "z-archive-forms-validation___es"
  }, {
    path: "/es/z-archive/forms/wizard",
    component: _40a6141d,
    name: "z-archive-forms-wizard___es"
  }, {
    path: "/es/z-archive/icons/boxicons",
    component: _03275a0c,
    name: "z-archive-icons-boxicons___es"
  }, {
    path: "/es/z-archive/icons/data-fontawesome",
    component: _46787261,
    name: "z-archive-icons-data-fontawesome___es"
  }, {
    path: "/es/z-archive/icons/data-material",
    component: _92931bdc,
    name: "z-archive-icons-data-material___es"
  }, {
    path: "/es/z-archive/icons/data-remix",
    component: _295a5aa8,
    name: "z-archive-icons-data-remix___es"
  }, {
    path: "/es/z-archive/icons/feather",
    component: _ebf12b54,
    name: "z-archive-icons-feather___es"
  }, {
    path: "/es/z-archive/icons/font-awesome",
    component: _3683f942,
    name: "z-archive-icons-font-awesome___es"
  }, {
    path: "/es/z-archive/icons/mdi",
    component: _6613a536,
    name: "z-archive-icons-mdi___es"
  }, {
    path: "/es/z-archive/icons/remix",
    component: _24ca5e88,
    name: "z-archive-icons-remix___es"
  }, {
    path: "/es/z-archive/icons/weather",
    component: _6d374927,
    name: "z-archive-icons-weather___es"
  }, {
    path: "/es/z-archive/maps/google",
    component: _31763a1d,
    name: "z-archive-maps-google___es"
  }, {
    path: "/es/z-archive/tables/advanced",
    component: _3961d924,
    name: "z-archive-tables-advanced___es"
  }, {
    path: "/es/z-archive/tables/basic",
    component: _2c58452c,
    name: "z-archive-tables-basic___es"
  }, {
    path: "/es/z-archive/task/detail",
    component: _a89f3bba,
    name: "z-archive-task-detail___es"
  }, {
    path: "/es/z-archive/task/kanban",
    component: _47fad259,
    name: "z-archive-task-kanban___es"
  }, {
    path: "/es/z-archive/task/list",
    component: _52b69b20,
    name: "z-archive-task-list___es"
  }, {
    path: "/es/z-archive/ui/avatars",
    component: _c570152e,
    name: "z-archive-ui-avatars___es"
  }, {
    path: "/es/z-archive/ui/buttons",
    component: _1cbb4f30,
    name: "z-archive-ui-buttons___es"
  }, {
    path: "/es/z-archive/ui/cards",
    component: _37812fd2,
    name: "z-archive-ui-cards___es"
  }, {
    path: "/es/z-archive/ui/carousel",
    component: _75c49141,
    name: "z-archive-ui-carousel___es"
  }, {
    path: "/es/z-archive/ui/dropdowns",
    component: _30ed5bf1,
    name: "z-archive-ui-dropdowns___es"
  }, {
    path: "/es/z-archive/ui/general",
    component: _8e1ee5d2,
    name: "z-archive-ui-general___es"
  }, {
    path: "/es/z-archive/ui/grid",
    component: _3e6964a7,
    name: "z-archive-ui-grid___es"
  }, {
    path: "/es/z-archive/ui/images",
    component: _0a192499,
    name: "z-archive-ui-images___es"
  }, {
    path: "/es/z-archive/ui/list-group",
    component: _21eb3631,
    name: "z-archive-ui-list-group___es"
  }, {
    path: "/es/z-archive/ui/modals",
    component: _09f7d687,
    name: "z-archive-ui-modals___es"
  }, {
    path: "/es/z-archive/ui/notifications",
    component: _75856852,
    name: "z-archive-ui-notifications___es"
  }, {
    path: "/es/z-archive/ui/portlets",
    component: _721b6d1a,
    name: "z-archive-ui-portlets___es"
  }, {
    path: "/es/z-archive/ui/progress",
    component: _3a05c38e,
    name: "z-archive-ui-progress___es"
  }, {
    path: "/es/z-archive/ui/ribbons",
    component: _3cf0380c,
    name: "z-archive-ui-ribbons___es"
  }, {
    path: "/es/z-archive/ui/spinners",
    component: _4b83b74a,
    name: "z-archive-ui-spinners___es"
  }, {
    path: "/es/z-archive/ui/tabs-accordions",
    component: _feda53ee,
    name: "z-archive-ui-tabs-accordions___es"
  }, {
    path: "/es/z-archive/ui/tooltips-popovers",
    component: _5b7c868c,
    name: "z-archive-ui-tooltips-popovers___es"
  }, {
    path: "/es/z-archive/ui/typography",
    component: _0a53f750,
    name: "z-archive-ui-typography___es"
  }, {
    path: "/es/z-archive/ui/video",
    component: _d6f7de2c,
    name: "z-archive-ui-video___es"
  }, {
    path: "/es/z-archive/widgets/data",
    component: _524242f3,
    name: "z-archive-widgets-data___es"
  }, {
    path: "/fr/z-archive/account/forgot-password",
    component: _5d3de145,
    name: "z-archive-account-forgot-password___fr"
  }, {
    path: "/fr/z-archive/account/login",
    component: _2fd29ea9,
    name: "z-archive-account-login___fr"
  }, {
    path: "/fr/z-archive/account/register",
    component: _2542e4da,
    name: "z-archive-account-register___fr"
  }, {
    path: "/fr/z-archive/apps/calendar",
    component: _2f5ad3a5,
    name: "z-archive-apps-calendar___fr"
  }, {
    path: "/fr/z-archive/apps/chat",
    component: _8469686a,
    name: "z-archive-apps-chat___fr"
  }, {
    path: "/fr/z-archive/apps/companies",
    component: _58f0ba96,
    name: "z-archive-apps-companies___fr"
  }, {
    path: "/fr/z-archive/apps/file-manager",
    component: _bcaa4e4a,
    name: "z-archive-apps-file-manager___fr"
  }, {
    path: "/fr/z-archive/apps/tickets",
    component: _531c33ca,
    name: "z-archive-apps-tickets___fr"
  }, {
    path: "/fr/z-archive/auth/confirm-mail",
    component: _05459a4e,
    name: "z-archive-auth-confirm-mail___fr"
  }, {
    path: "/fr/z-archive/auth/confirm-mail-2",
    component: _1548d1be,
    name: "z-archive-auth-confirm-mail-2___fr"
  }, {
    path: "/fr/z-archive/auth/lock-screen",
    component: _2670ecae,
    name: "z-archive-auth-lock-screen___fr"
  }, {
    path: "/fr/z-archive/auth/lock-screen-2",
    component: _590e96e4,
    name: "z-archive-auth-lock-screen-2___fr"
  }, {
    path: "/fr/z-archive/auth/login",
    component: _96f29af8,
    name: "z-archive-auth-login___fr"
  }, {
    path: "/fr/z-archive/auth/login-2",
    component: _afdddaae,
    name: "z-archive-auth-login-2___fr"
  }, {
    path: "/fr/z-archive/auth/logout",
    component: _2960a67f,
    name: "z-archive-auth-logout___fr"
  }, {
    path: "/fr/z-archive/auth/logout-2",
    component: _4e3df3e4,
    name: "z-archive-auth-logout-2___fr"
  }, {
    path: "/fr/z-archive/auth/recoverpwd",
    component: _210cf64e,
    name: "z-archive-auth-recoverpwd___fr"
  }, {
    path: "/fr/z-archive/auth/recoverpwd-2",
    component: _0c158bf3,
    name: "z-archive-auth-recoverpwd-2___fr"
  }, {
    path: "/fr/z-archive/auth/register",
    component: _759db050,
    name: "z-archive-auth-register___fr"
  }, {
    path: "/fr/z-archive/auth/register-2",
    component: _37f382fd,
    name: "z-archive-auth-register-2___fr"
  }, {
    path: "/fr/z-archive/auth/signin-signup",
    component: _91c55684,
    name: "z-archive-auth-signin-signup___fr"
  }, {
    path: "/fr/z-archive/auth/signin-signup-2",
    component: _5f880e63,
    name: "z-archive-auth-signin-signup-2___fr"
  }, {
    path: "/fr/z-archive/charts/apex",
    component: _1b43ad7e,
    name: "z-archive-charts-apex___fr"
  }, {
    path: "/fr/z-archive/charts/c3",
    component: _79ee5b30,
    name: "z-archive-charts-c3___fr"
  }, {
    path: "/fr/z-archive/charts/chartist",
    component: _54d00518,
    name: "z-archive-charts-chartist___fr"
  }, {
    path: "/fr/z-archive/charts/chartjs",
    component: _38dfc3a6,
    name: "z-archive-charts-chartjs___fr"
  }, {
    path: "/fr/z-archive/charts/knob",
    component: _1cf445d8,
    name: "z-archive-charts-knob___fr"
  }, {
    path: "/fr/z-archive/contacts/list",
    component: _6e58713e,
    name: "z-archive-contacts-list___fr"
  }, {
    path: "/fr/z-archive/contacts/profile",
    component: _0fee35b9,
    name: "z-archive-contacts-profile___fr"
  }, {
    path: "/fr/z-archive/dashboard/analytics",
    component: _279933e3,
    name: "z-archive-dashboard-analytics___fr"
  }, {
    path: "/fr/z-archive/dashboard/crm",
    component: _071e41cb,
    name: "z-archive-dashboard-crm___fr"
  }, {
    path: "/fr/z-archive/dashboard/default",
    component: _6a0e8a08,
    name: "z-archive-dashboard-default___fr"
  }, {
    path: "/fr/z-archive/ecommerce/cart",
    component: _59610123,
    name: "z-archive-ecommerce-cart___fr"
  }, {
    path: "/fr/z-archive/ecommerce/checkout",
    component: _1bb2ba6e,
    name: "z-archive-ecommerce-checkout___fr"
  }, {
    path: "/fr/z-archive/ecommerce/customers",
    component: _1c00e340,
    name: "z-archive-ecommerce-customers___fr"
  }, {
    path: "/fr/z-archive/ecommerce/data-products",
    component: _85914e4a,
    name: "z-archive-ecommerce-data-products___fr"
  }, {
    path: "/fr/z-archive/ecommerce/order-detail",
    component: _5c57eab3,
    name: "z-archive-ecommerce-order-detail___fr"
  }, {
    path: "/fr/z-archive/ecommerce/orders",
    component: _3b04d04c,
    name: "z-archive-ecommerce-orders___fr"
  }, {
    path: "/fr/z-archive/ecommerce/product-create",
    component: _5e0f5a46,
    name: "z-archive-ecommerce-product-create___fr"
  }, {
    path: "/fr/z-archive/ecommerce/products",
    component: _b5b7ea8a,
    name: "z-archive-ecommerce-products___fr"
  }, {
    path: "/fr/z-archive/ecommerce/products-grid",
    component: _8d631bc8,
    name: "z-archive-ecommerce-products-grid___fr"
  }, {
    path: "/fr/z-archive/ecommerce/sellers",
    component: _467fabbe,
    name: "z-archive-ecommerce-sellers___fr"
  }, {
    path: "/fr/z-archive/email/data-inbox",
    component: _0c3174e6,
    name: "z-archive-email-data-inbox___fr"
  }, {
    path: "/fr/z-archive/email/inbox",
    component: _3395f092,
    name: "z-archive-email-inbox___fr"
  }, {
    path: "/fr/z-archive/email/sidepanel",
    component: _47afc03e,
    name: "z-archive-email-sidepanel___fr"
  }, {
    path: "/fr/z-archive/email/templates",
    component: _8156bb2c,
    name: "z-archive-email-templates___fr"
  }, {
    path: "/fr/z-archive/email/toolbar",
    component: _bc2a2828,
    name: "z-archive-email-toolbar___fr"
  }, {
    path: "/fr/z-archive/extended/rangeslider",
    component: _6b4a39c8,
    name: "z-archive-extended-rangeslider___fr"
  }, {
    path: "/fr/z-archive/extended/scrollspy",
    component: _4cd8c58e,
    name: "z-archive-extended-scrollspy___fr"
  }, {
    path: "/fr/z-archive/extended/sweet-alert",
    component: _6527adae,
    name: "z-archive-extended-sweet-alert___fr"
  }, {
    path: "/fr/z-archive/extended/tour",
    component: _e68f3944,
    name: "z-archive-extended-tour___fr"
  }, {
    path: "/fr/z-archive/extras/404",
    component: _013e3478,
    name: "z-archive-extras-404___fr"
  }, {
    path: "/fr/z-archive/extras/404-alt",
    component: _4869a4d4,
    name: "z-archive-extras-404-alt___fr"
  }, {
    path: "/fr/z-archive/extras/500",
    component: _35ec11b5,
    name: "z-archive-extras-500___fr"
  }, {
    path: "/fr/z-archive/extras/coming-soon",
    component: _2b407087,
    name: "z-archive-extras-coming-soon___fr"
  }, {
    path: "/fr/z-archive/extras/faqs",
    component: _075096e6,
    name: "z-archive-extras-faqs___fr"
  }, {
    path: "/fr/z-archive/extras/invoice",
    component: _437dd026,
    name: "z-archive-extras-invoice___fr"
  }, {
    path: "/fr/z-archive/extras/lightbox",
    component: _111bed65,
    name: "z-archive-extras-lightbox___fr"
  }, {
    path: "/fr/z-archive/extras/maintenance",
    component: _6292d0d3,
    name: "z-archive-extras-maintenance___fr"
  }, {
    path: "/fr/z-archive/extras/pricing",
    component: _6e818006,
    name: "z-archive-extras-pricing___fr"
  }, {
    path: "/fr/z-archive/extras/search-results",
    component: _06da3141,
    name: "z-archive-extras-search-results___fr"
  }, {
    path: "/fr/z-archive/extras/sitemap",
    component: _f9930516,
    name: "z-archive-extras-sitemap___fr"
  }, {
    path: "/fr/z-archive/extras/starter",
    component: _7e16d762,
    name: "z-archive-extras-starter___fr"
  }, {
    path: "/fr/z-archive/extras/timeline",
    component: _7c1612b1,
    name: "z-archive-extras-timeline___fr"
  }, {
    path: "/fr/z-archive/forms/advanced",
    component: _563bf658,
    name: "z-archive-forms-advanced___fr"
  }, {
    path: "/fr/z-archive/forms/elements",
    component: _0e88eb29,
    name: "z-archive-forms-elements___fr"
  }, {
    path: "/fr/z-archive/forms/file-uploads",
    component: _7ad82773,
    name: "z-archive-forms-file-uploads___fr"
  }, {
    path: "/fr/z-archive/forms/mask",
    component: _d7da68c4,
    name: "z-archive-forms-mask___fr"
  }, {
    path: "/fr/z-archive/forms/quill",
    component: _50ef6a43,
    name: "z-archive-forms-quill___fr"
  }, {
    path: "/fr/z-archive/forms/validation",
    component: _13f5832b,
    name: "z-archive-forms-validation___fr"
  }, {
    path: "/fr/z-archive/forms/wizard",
    component: _40a6141d,
    name: "z-archive-forms-wizard___fr"
  }, {
    path: "/fr/z-archive/icons/boxicons",
    component: _03275a0c,
    name: "z-archive-icons-boxicons___fr"
  }, {
    path: "/fr/z-archive/icons/data-fontawesome",
    component: _46787261,
    name: "z-archive-icons-data-fontawesome___fr"
  }, {
    path: "/fr/z-archive/icons/data-material",
    component: _92931bdc,
    name: "z-archive-icons-data-material___fr"
  }, {
    path: "/fr/z-archive/icons/data-remix",
    component: _295a5aa8,
    name: "z-archive-icons-data-remix___fr"
  }, {
    path: "/fr/z-archive/icons/feather",
    component: _ebf12b54,
    name: "z-archive-icons-feather___fr"
  }, {
    path: "/fr/z-archive/icons/font-awesome",
    component: _3683f942,
    name: "z-archive-icons-font-awesome___fr"
  }, {
    path: "/fr/z-archive/icons/mdi",
    component: _6613a536,
    name: "z-archive-icons-mdi___fr"
  }, {
    path: "/fr/z-archive/icons/remix",
    component: _24ca5e88,
    name: "z-archive-icons-remix___fr"
  }, {
    path: "/fr/z-archive/icons/weather",
    component: _6d374927,
    name: "z-archive-icons-weather___fr"
  }, {
    path: "/fr/z-archive/maps/google",
    component: _31763a1d,
    name: "z-archive-maps-google___fr"
  }, {
    path: "/fr/z-archive/tables/advanced",
    component: _3961d924,
    name: "z-archive-tables-advanced___fr"
  }, {
    path: "/fr/z-archive/tables/basic",
    component: _2c58452c,
    name: "z-archive-tables-basic___fr"
  }, {
    path: "/fr/z-archive/task/detail",
    component: _a89f3bba,
    name: "z-archive-task-detail___fr"
  }, {
    path: "/fr/z-archive/task/kanban",
    component: _47fad259,
    name: "z-archive-task-kanban___fr"
  }, {
    path: "/fr/z-archive/task/list",
    component: _52b69b20,
    name: "z-archive-task-list___fr"
  }, {
    path: "/fr/z-archive/ui/avatars",
    component: _c570152e,
    name: "z-archive-ui-avatars___fr"
  }, {
    path: "/fr/z-archive/ui/buttons",
    component: _1cbb4f30,
    name: "z-archive-ui-buttons___fr"
  }, {
    path: "/fr/z-archive/ui/cards",
    component: _37812fd2,
    name: "z-archive-ui-cards___fr"
  }, {
    path: "/fr/z-archive/ui/carousel",
    component: _75c49141,
    name: "z-archive-ui-carousel___fr"
  }, {
    path: "/fr/z-archive/ui/dropdowns",
    component: _30ed5bf1,
    name: "z-archive-ui-dropdowns___fr"
  }, {
    path: "/fr/z-archive/ui/general",
    component: _8e1ee5d2,
    name: "z-archive-ui-general___fr"
  }, {
    path: "/fr/z-archive/ui/grid",
    component: _3e6964a7,
    name: "z-archive-ui-grid___fr"
  }, {
    path: "/fr/z-archive/ui/images",
    component: _0a192499,
    name: "z-archive-ui-images___fr"
  }, {
    path: "/fr/z-archive/ui/list-group",
    component: _21eb3631,
    name: "z-archive-ui-list-group___fr"
  }, {
    path: "/fr/z-archive/ui/modals",
    component: _09f7d687,
    name: "z-archive-ui-modals___fr"
  }, {
    path: "/fr/z-archive/ui/notifications",
    component: _75856852,
    name: "z-archive-ui-notifications___fr"
  }, {
    path: "/fr/z-archive/ui/portlets",
    component: _721b6d1a,
    name: "z-archive-ui-portlets___fr"
  }, {
    path: "/fr/z-archive/ui/progress",
    component: _3a05c38e,
    name: "z-archive-ui-progress___fr"
  }, {
    path: "/fr/z-archive/ui/ribbons",
    component: _3cf0380c,
    name: "z-archive-ui-ribbons___fr"
  }, {
    path: "/fr/z-archive/ui/spinners",
    component: _4b83b74a,
    name: "z-archive-ui-spinners___fr"
  }, {
    path: "/fr/z-archive/ui/tabs-accordions",
    component: _feda53ee,
    name: "z-archive-ui-tabs-accordions___fr"
  }, {
    path: "/fr/z-archive/ui/tooltips-popovers",
    component: _5b7c868c,
    name: "z-archive-ui-tooltips-popovers___fr"
  }, {
    path: "/fr/z-archive/ui/typography",
    component: _0a53f750,
    name: "z-archive-ui-typography___fr"
  }, {
    path: "/fr/z-archive/ui/video",
    component: _d6f7de2c,
    name: "z-archive-ui-video___fr"
  }, {
    path: "/fr/z-archive/widgets/data",
    component: _524242f3,
    name: "z-archive-widgets-data___fr"
  }, {
    path: "/z-archive/apps/calendar/data-calendar",
    component: _6c5366bb,
    name: "z-archive-apps-calendar-data-calendar___en"
  }, {
    path: "/z-archive/apps/chat/data",
    component: _3a8fbfae,
    name: "z-archive-apps-chat-data___en"
  }, {
    path: "/z-archive/apps/companies/data",
    component: _bd6f358e,
    name: "z-archive-apps-companies-data___en"
  }, {
    path: "/z-archive/apps/tickets/data",
    component: _72a89b6d,
    name: "z-archive-apps-tickets-data___en"
  }, {
    path: "/z-archive/charts/apex/data",
    component: _ebea1bbe,
    name: "z-archive-charts-apex-data___en"
  }, {
    path: "/z-archive/charts/c3/data",
    component: _0e896453,
    name: "z-archive-charts-c3-data___en"
  }, {
    path: "/z-archive/charts/chartist/data",
    component: _71fec797,
    name: "z-archive-charts-chartist-data___en"
  }, {
    path: "/z-archive/charts/chartjs/BarChart",
    component: _978bdbc0,
    name: "z-archive-charts-chartjs-BarChart___en"
  }, {
    path: "/z-archive/charts/chartjs/DonutChart",
    component: _43c0569e,
    name: "z-archive-charts-chartjs-DonutChart___en"
  }, {
    path: "/z-archive/charts/chartjs/LineChart",
    component: _662c2005,
    name: "z-archive-charts-chartjs-LineChart___en"
  }, {
    path: "/z-archive/charts/chartjs/PieChart",
    component: _5f5bf4c7,
    name: "z-archive-charts-chartjs-PieChart___en"
  }, {
    path: "/z-archive/charts/chartjs/PolarChart",
    component: _4a9db7d6,
    name: "z-archive-charts-chartjs-PolarChart___en"
  }, {
    path: "/z-archive/charts/chartjs/RadarChart",
    component: _55b5314d,
    name: "z-archive-charts-chartjs-RadarChart___en"
  }, {
    path: "/z-archive/dashboard/analytics/channels",
    component: _08c9be4f,
    name: "z-archive-dashboard-analytics-channels___en"
  }, {
    path: "/z-archive/dashboard/analytics/overview",
    component: _9a80e910,
    name: "z-archive-dashboard-analytics-overview___en"
  }, {
    path: "/z-archive/dashboard/analytics/social-media",
    component: _3a80ea83,
    name: "z-archive-dashboard-analytics-social-media___en"
  }, {
    path: "/z-archive/dashboard/analytics/sources",
    component: _de076cee,
    name: "z-archive-dashboard-analytics-sources___en"
  }, {
    path: "/z-archive/dashboard/analytics/users",
    component: _6d030e19,
    name: "z-archive-dashboard-analytics-users___en"
  }, {
    path: "/z-archive/ecommerce/customers/data",
    component: _02a4b8fa,
    name: "z-archive-ecommerce-customers-data___en"
  }, {
    path: "/z-archive/ecommerce/orders/data",
    component: _3833c37d,
    name: "z-archive-ecommerce-orders-data___en"
  }, {
    path: "/z-archive/ecommerce/products/data",
    component: _ec290ac4,
    name: "z-archive-ecommerce-products-data___en"
  }, {
    path: "/z-archive/tables/advanced/data",
    component: _76d1d7de,
    name: "z-archive-tables-advanced-data___en"
  }, {
    path: "/z-archive/task/kanban/data",
    component: _6728dc88,
    name: "z-archive-task-kanban-data___en"
  }, {
    path: "/ar/z-archive/apps/calendar/data-calendar",
    component: _6c5366bb,
    name: "z-archive-apps-calendar-data-calendar___ar"
  }, {
    path: "/ar/z-archive/apps/chat/data",
    component: _3a8fbfae,
    name: "z-archive-apps-chat-data___ar"
  }, {
    path: "/ar/z-archive/apps/companies/data",
    component: _bd6f358e,
    name: "z-archive-apps-companies-data___ar"
  }, {
    path: "/ar/z-archive/apps/tickets/data",
    component: _72a89b6d,
    name: "z-archive-apps-tickets-data___ar"
  }, {
    path: "/ar/z-archive/charts/apex/data",
    component: _ebea1bbe,
    name: "z-archive-charts-apex-data___ar"
  }, {
    path: "/ar/z-archive/charts/c3/data",
    component: _0e896453,
    name: "z-archive-charts-c3-data___ar"
  }, {
    path: "/ar/z-archive/charts/chartist/data",
    component: _71fec797,
    name: "z-archive-charts-chartist-data___ar"
  }, {
    path: "/ar/z-archive/charts/chartjs/BarChart",
    component: _978bdbc0,
    name: "z-archive-charts-chartjs-BarChart___ar"
  }, {
    path: "/ar/z-archive/charts/chartjs/DonutChart",
    component: _43c0569e,
    name: "z-archive-charts-chartjs-DonutChart___ar"
  }, {
    path: "/ar/z-archive/charts/chartjs/LineChart",
    component: _662c2005,
    name: "z-archive-charts-chartjs-LineChart___ar"
  }, {
    path: "/ar/z-archive/charts/chartjs/PieChart",
    component: _5f5bf4c7,
    name: "z-archive-charts-chartjs-PieChart___ar"
  }, {
    path: "/ar/z-archive/charts/chartjs/PolarChart",
    component: _4a9db7d6,
    name: "z-archive-charts-chartjs-PolarChart___ar"
  }, {
    path: "/ar/z-archive/charts/chartjs/RadarChart",
    component: _55b5314d,
    name: "z-archive-charts-chartjs-RadarChart___ar"
  }, {
    path: "/ar/z-archive/dashboard/analytics/channels",
    component: _08c9be4f,
    name: "z-archive-dashboard-analytics-channels___ar"
  }, {
    path: "/ar/z-archive/dashboard/analytics/overview",
    component: _9a80e910,
    name: "z-archive-dashboard-analytics-overview___ar"
  }, {
    path: "/ar/z-archive/dashboard/analytics/social-media",
    component: _3a80ea83,
    name: "z-archive-dashboard-analytics-social-media___ar"
  }, {
    path: "/ar/z-archive/dashboard/analytics/sources",
    component: _de076cee,
    name: "z-archive-dashboard-analytics-sources___ar"
  }, {
    path: "/ar/z-archive/dashboard/analytics/users",
    component: _6d030e19,
    name: "z-archive-dashboard-analytics-users___ar"
  }, {
    path: "/ar/z-archive/ecommerce/customers/data",
    component: _02a4b8fa,
    name: "z-archive-ecommerce-customers-data___ar"
  }, {
    path: "/ar/z-archive/ecommerce/orders/data",
    component: _3833c37d,
    name: "z-archive-ecommerce-orders-data___ar"
  }, {
    path: "/ar/z-archive/ecommerce/products/data",
    component: _ec290ac4,
    name: "z-archive-ecommerce-products-data___ar"
  }, {
    path: "/ar/z-archive/tables/advanced/data",
    component: _76d1d7de,
    name: "z-archive-tables-advanced-data___ar"
  }, {
    path: "/ar/z-archive/task/kanban/data",
    component: _6728dc88,
    name: "z-archive-task-kanban-data___ar"
  }, {
    path: "/es/z-archive/apps/calendar/data-calendar",
    component: _6c5366bb,
    name: "z-archive-apps-calendar-data-calendar___es"
  }, {
    path: "/es/z-archive/apps/chat/data",
    component: _3a8fbfae,
    name: "z-archive-apps-chat-data___es"
  }, {
    path: "/es/z-archive/apps/companies/data",
    component: _bd6f358e,
    name: "z-archive-apps-companies-data___es"
  }, {
    path: "/es/z-archive/apps/tickets/data",
    component: _72a89b6d,
    name: "z-archive-apps-tickets-data___es"
  }, {
    path: "/es/z-archive/charts/apex/data",
    component: _ebea1bbe,
    name: "z-archive-charts-apex-data___es"
  }, {
    path: "/es/z-archive/charts/c3/data",
    component: _0e896453,
    name: "z-archive-charts-c3-data___es"
  }, {
    path: "/es/z-archive/charts/chartist/data",
    component: _71fec797,
    name: "z-archive-charts-chartist-data___es"
  }, {
    path: "/es/z-archive/charts/chartjs/BarChart",
    component: _978bdbc0,
    name: "z-archive-charts-chartjs-BarChart___es"
  }, {
    path: "/es/z-archive/charts/chartjs/DonutChart",
    component: _43c0569e,
    name: "z-archive-charts-chartjs-DonutChart___es"
  }, {
    path: "/es/z-archive/charts/chartjs/LineChart",
    component: _662c2005,
    name: "z-archive-charts-chartjs-LineChart___es"
  }, {
    path: "/es/z-archive/charts/chartjs/PieChart",
    component: _5f5bf4c7,
    name: "z-archive-charts-chartjs-PieChart___es"
  }, {
    path: "/es/z-archive/charts/chartjs/PolarChart",
    component: _4a9db7d6,
    name: "z-archive-charts-chartjs-PolarChart___es"
  }, {
    path: "/es/z-archive/charts/chartjs/RadarChart",
    component: _55b5314d,
    name: "z-archive-charts-chartjs-RadarChart___es"
  }, {
    path: "/es/z-archive/dashboard/analytics/channels",
    component: _08c9be4f,
    name: "z-archive-dashboard-analytics-channels___es"
  }, {
    path: "/es/z-archive/dashboard/analytics/overview",
    component: _9a80e910,
    name: "z-archive-dashboard-analytics-overview___es"
  }, {
    path: "/es/z-archive/dashboard/analytics/social-media",
    component: _3a80ea83,
    name: "z-archive-dashboard-analytics-social-media___es"
  }, {
    path: "/es/z-archive/dashboard/analytics/sources",
    component: _de076cee,
    name: "z-archive-dashboard-analytics-sources___es"
  }, {
    path: "/es/z-archive/dashboard/analytics/users",
    component: _6d030e19,
    name: "z-archive-dashboard-analytics-users___es"
  }, {
    path: "/es/z-archive/ecommerce/customers/data",
    component: _02a4b8fa,
    name: "z-archive-ecommerce-customers-data___es"
  }, {
    path: "/es/z-archive/ecommerce/orders/data",
    component: _3833c37d,
    name: "z-archive-ecommerce-orders-data___es"
  }, {
    path: "/es/z-archive/ecommerce/products/data",
    component: _ec290ac4,
    name: "z-archive-ecommerce-products-data___es"
  }, {
    path: "/es/z-archive/tables/advanced/data",
    component: _76d1d7de,
    name: "z-archive-tables-advanced-data___es"
  }, {
    path: "/es/z-archive/task/kanban/data",
    component: _6728dc88,
    name: "z-archive-task-kanban-data___es"
  }, {
    path: "/fr/z-archive/apps/calendar/data-calendar",
    component: _6c5366bb,
    name: "z-archive-apps-calendar-data-calendar___fr"
  }, {
    path: "/fr/z-archive/apps/chat/data",
    component: _3a8fbfae,
    name: "z-archive-apps-chat-data___fr"
  }, {
    path: "/fr/z-archive/apps/companies/data",
    component: _bd6f358e,
    name: "z-archive-apps-companies-data___fr"
  }, {
    path: "/fr/z-archive/apps/tickets/data",
    component: _72a89b6d,
    name: "z-archive-apps-tickets-data___fr"
  }, {
    path: "/fr/z-archive/charts/apex/data",
    component: _ebea1bbe,
    name: "z-archive-charts-apex-data___fr"
  }, {
    path: "/fr/z-archive/charts/c3/data",
    component: _0e896453,
    name: "z-archive-charts-c3-data___fr"
  }, {
    path: "/fr/z-archive/charts/chartist/data",
    component: _71fec797,
    name: "z-archive-charts-chartist-data___fr"
  }, {
    path: "/fr/z-archive/charts/chartjs/BarChart",
    component: _978bdbc0,
    name: "z-archive-charts-chartjs-BarChart___fr"
  }, {
    path: "/fr/z-archive/charts/chartjs/DonutChart",
    component: _43c0569e,
    name: "z-archive-charts-chartjs-DonutChart___fr"
  }, {
    path: "/fr/z-archive/charts/chartjs/LineChart",
    component: _662c2005,
    name: "z-archive-charts-chartjs-LineChart___fr"
  }, {
    path: "/fr/z-archive/charts/chartjs/PieChart",
    component: _5f5bf4c7,
    name: "z-archive-charts-chartjs-PieChart___fr"
  }, {
    path: "/fr/z-archive/charts/chartjs/PolarChart",
    component: _4a9db7d6,
    name: "z-archive-charts-chartjs-PolarChart___fr"
  }, {
    path: "/fr/z-archive/charts/chartjs/RadarChart",
    component: _55b5314d,
    name: "z-archive-charts-chartjs-RadarChart___fr"
  }, {
    path: "/fr/z-archive/dashboard/analytics/channels",
    component: _08c9be4f,
    name: "z-archive-dashboard-analytics-channels___fr"
  }, {
    path: "/fr/z-archive/dashboard/analytics/overview",
    component: _9a80e910,
    name: "z-archive-dashboard-analytics-overview___fr"
  }, {
    path: "/fr/z-archive/dashboard/analytics/social-media",
    component: _3a80ea83,
    name: "z-archive-dashboard-analytics-social-media___fr"
  }, {
    path: "/fr/z-archive/dashboard/analytics/sources",
    component: _de076cee,
    name: "z-archive-dashboard-analytics-sources___fr"
  }, {
    path: "/fr/z-archive/dashboard/analytics/users",
    component: _6d030e19,
    name: "z-archive-dashboard-analytics-users___fr"
  }, {
    path: "/fr/z-archive/ecommerce/customers/data",
    component: _02a4b8fa,
    name: "z-archive-ecommerce-customers-data___fr"
  }, {
    path: "/fr/z-archive/ecommerce/orders/data",
    component: _3833c37d,
    name: "z-archive-ecommerce-orders-data___fr"
  }, {
    path: "/fr/z-archive/ecommerce/products/data",
    component: _ec290ac4,
    name: "z-archive-ecommerce-products-data___fr"
  }, {
    path: "/fr/z-archive/tables/advanced/data",
    component: _76d1d7de,
    name: "z-archive-tables-advanced-data___fr"
  }, {
    path: "/fr/z-archive/task/kanban/data",
    component: _6728dc88,
    name: "z-archive-task-kanban-data___fr"
  }, {
    path: "/ar/z-archive/ecommerce/product-detail/:id?",
    component: _2c0d76f8,
    name: "z-archive-ecommerce-product-detail-id___ar"
  }, {
    path: "/ar/z-archive/email/reademail/:id?",
    component: _3563f153,
    name: "z-archive-email-reademail-id___ar"
  }, {
    path: "/es/z-archive/ecommerce/product-detail/:id?",
    component: _2c0d76f8,
    name: "z-archive-ecommerce-product-detail-id___es"
  }, {
    path: "/es/z-archive/email/reademail/:id?",
    component: _3563f153,
    name: "z-archive-email-reademail-id___es"
  }, {
    path: "/fr/z-archive/ecommerce/product-detail/:id?",
    component: _2c0d76f8,
    name: "z-archive-ecommerce-product-detail-id___fr"
  }, {
    path: "/fr/z-archive/email/reademail/:id?",
    component: _3563f153,
    name: "z-archive-email-reademail-id___fr"
  }, {
    path: "/z-archive/ecommerce/product-detail/:id?",
    component: _2c0d76f8,
    name: "z-archive-ecommerce-product-detail-id___en"
  }, {
    path: "/z-archive/email/reademail/:id?",
    component: _3563f153,
    name: "z-archive-email-reademail-id___en"
  }, {
    path: "/",
    component: _6a1085f0,
    name: "index___en"
  }, {
    path: "/",
    component: _2563ddd0
  }],

  fallback: false
}

function decodeObj(obj) {
  for (const key in obj) {
    if (typeof obj[key] === 'string') {
      obj[key] = decode(obj[key])
    }
  }
}

export function createRouter () {
  const router = new Router(routerOptions)

  const resolve = router.resolve.bind(router)
  router.resolve = (to, current, append) => {
    if (typeof to === 'string') {
      to = normalizeURL(to)
    }
    const r = resolve(to, current, append)
    if (r && r.resolved && r.resolved.query) {
      decodeObj(r.resolved.query)
    }
    return r
  }

  return router
}
